<?php $account = $this->auth()->getManager(); ?>
  <div data-collapse="medium" data-animation="default" data-duration="400" role="banner" class="nav-bar w-nav">
    <div class="nav-container"><a href="/" aria-current="page" class="nav-logo-link w-nav-brand w--current"><img src="/vufind/themes/coronawhy/images/logo-32x-p-800.png" width="643" srcset="images/logo-32x-p-500.png 500w, /vufind/themes/coronawhy/images/logo-32x-p-800.png 800w, images/logo-32x-p-1080.png 1080w, images/logo-32x.png 1286w" sizes="(max-width: 479px) 63vw, (max-width: 767px) 150px, (max-width: 991px) 200px, 20vw" alt="" class="nav-logo"></a>
      <nav role="navigation" class="nav-menu w-nav-menu"><a href="https://www.coronawhy.org" aria-current="page" class="nav-link w-nav-link w--current">Home</a><a href="https://www.coronawhy.org/daily-progress" class="nav-link w-nav-link">Daily Progress</a>
        <div data-hover="" data-delay="0" class="w-dropdown">
          <div class="w-dropdown-toggle">
            <div class="w-icon-dropdown-toggle"></div>
            <div>Solutions</div>
          </div>
          <nav class="w-dropdown-list"><a href="https://www.coronawhy.org/services" class="w-dropdown-link">Services</a><a href="https://www.coronawhy.org/literature-review-demo" class="w-dropdown-link">Literature Review Demo</a></nav>
        </div>
        <div data-hover="" data-delay="0" class="w-dropdown">
          <div class="w-dropdown-toggle">
            <div class="w-icon-dropdown-toggle"></div>
            <div>Data</div>
          </div>
          <nav class="w-dropdown-list"><a href="https://www.coronawhy.org/covid-19-datasets" class="w-dropdown-link">COVID-19 datasets</a><a href="https://www.coronawhy.org/cord19" class="w-dropdown-link">CORD-19 affiliations map</a></nav>
        </div><a href="/team" class="nav-link w-nav-link">Team</a>
        <div class="nav__dropdown-list"></div>
        <div class="nav__button-wrap"><a href="https://www.coronawhy.org/join-the-fight" class="button is--nav w-button">Join the Fight!</a></div>
      </nav>
      <div class="nav-menu__button w-nav-button">
        <div class="w-icon-nav-menu"></div>
      </div>
    </div>
  </div>
<div class="banner container navbar">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse" aria-hidden="true">
      <i class="fa fa-bars"></i>
    </button>
  </div>
  <?php if (!isset($this->layout()->renderingError)): ?>
    <div class="collapse navbar-collapse" id="header-collapse">
      <nav>
        <ul class="nav navbar-nav navbar-right flip">
          <?php if ($this->feedback()->tabEnabled()): ?>
            <li>
              <a id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope" aria-hidden="true"></i> <?=$this->transEsc("Feedback")?></a>
            </li>
          <?php endif; ?>
          <?php $cart = $this->cart(); if ($cart->isActive()): ?>
            <li id="cartSummary">
              <a id="cartItems" data-lightbox title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>">
                <i class="fa fa-suitcase" aria-hidden="true"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?>
                <span class="full<?=!$cart->isFull() ? ' hidden' : '' ?>">(<?=$this->transEsc('bookbag_full') ?>)</span>
              </a>
            </li>
          <?php endif; ?>
          <?php if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
            <li class="logoutOptions<?php if($account->dropdownEnabled()): ?> with-dropdown<?php endif ?><?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
              <a href="<?=$this->url('myresearch-home', [], ['query' => ['redirect' => 0]])?>"><i id="account-icon" class="fa fa-user-circle" aria-hidden="true"></i> <?=$this->transEsc("Your Account")?></a>
            </li>
            <?php if($account->dropdownEnabled()): ?>
              <li id="login-dropdown" class="dropdown<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
                <a href="#" data-toggle="dropdown"><i class="fa fa-caret-down"></i></a>
                <div class="dropdown-menu">
                  <?=$this->render('myresearch/menu'); ?>
                </div>
              </li>
            <?php endif; ?>
            <li class="logoutOptions<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
              <a href="<?=$this->url('myresearch-logout')?>" class="logout"><i class="fa fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?></a>
            </li>
            <li id="loginOptions"<?php if($account->isLoggedIn()): ?> class="hidden"<?php endif ?>>
              <?php if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                <a href="<?=$this->url('myresearch-userlogin')?>"><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Institutional Login")?></a>
              <?php else: ?>
                <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Login")?></a>
              <?php endif; ?>
            </li>
          <?php endif; ?>

          <?php if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
            <li class="theme dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <?php foreach ($this->layout()->themeOptions as $current): ?>
                  <li<?=$current['selected'] ? ' class="active"' : ''?>>
                    <a href="<?=$this->escapeHtmlAttr($this->url()->addQueryParameters(['ui' => $current['name']])) ?>" rel="nofollow">
                      <?=$this->transEsc($current['desc']) ?>
                    </a>
                  </li>
                <?php endforeach; ?>
              </ul>
            </li>
          <?php endif; ?>

          <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
            <li class="language dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <?php foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                  <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>>
                    <a href="<?=$this->escapeHtmlAttr($this->url()->addQueryParameters(['lng' => $langCode])) ?>" rel="nofollow">
                      <?=$this->displayLanguageOption($langName) ?>
                    </a>
                  </li>
                <?php endforeach; ?>
              </ul>
            </li>
          <?php endif; ?>
        </ul>
      </nav>
    </div>
  <?php endif; ?>
</div>
<?php if ($this->layout()->searchbox !== false): ?>
  <div class="search container navbar">
    <div class="nav searchbox hidden-print" role="search">
      <?=$this->layout()->searchbox ?>
    </div>
  </div>
<?php endif; ?>
